### PR TITLE
update now page and robot.txt

### LINKED ISSUE #180: Add robots.txt file
Screen Shot 2021-08-09 at 23 47 50

### PR DESCRIPTION
**Pull request by inezabonte**
## Description
- I updated the /now page
- I added a robots.txt file

## Linked Issue

fixes #180

## checklist

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
https://twitter.com/NowNowNow/status/1425124795943895041 :partying_face:

**Comment by inezabonte** [comment]
Small wins 😄

**Comment by inezabonte** [comment]
Any thoughts about the new changes in the theme on the site also my new headshot @Ryuno-Ki ?

**Comment by Ryuno-Ki** [comment]
Waiting 8.6s (after several failed DNS lookups) don't feel good…
https://coolors.co/contrast-checker/9ca3af-333333 is okay, but could be better.

If you pick a colour and shift the grey a tiny bit in that direction, that might change the mood (e.g. change to hsl, set the hue and tweak the saturation, then convert back to rgb).
Right now, you don't have any accent colour. You could add it to certain elements (e.g. the borderline in block quotes) once you picked something.

**Comment by inezabonte** [comment]
Failed DNS lookup could have been caused by me deleting the www. subdomain. 🤭
I'll fix that. Thanks. I'll explore different colours and see what fits

**Pull request merged**
